language: ruby
rvm:
  - 2.5.0

services:
  - postgresql

before_install:
  - gem update --system

before_script:
  - psql -c "CREATE USER \"cq-rails\" WITH PASSWORD 'cq-rails';" -U postgres
  - psql -c "DROP DATABASE IF EXISTS \"cq-rails_test\";" -U postgres
  - psql -c "CREATE DATABASE \"cq-rails_test\" ENCODING 'utf8';" -U postgres
  - bundle exec rails db:migrate

script:
  # - bundle exec rspec spec -fd
  - bundle exec rubocop app spec -R --format simple
